version: '3'
services:
  flask:
    build:
      context: ./flask-demo-app
    ports:
      - "8080:5000"
  nginx:
    image: nginx:latest
    volumes:
      - "/home/vagrant/course/projekti/flask-demo-app/templates:/usr/share/nginx/html:ro"
